### PR TITLE
add char ptr convert example

### PR DESCRIPTION
**Pull request by TeavenX**
a simple supplement for #150 https://github.com/ebitengine/purego/issues/150

### CODE REVIEW

**Comment by hajimehoshi** [comment]
This example can be compiled but actually doesn't work.

If we want to add such a simple example like this, Example_* to purego_test would be fine.

**Comment by TotallyGamerJet** [comment]
The comment is wrong. You need to use just plain old string. Internally, purego copies the *char into an allocated string object. *string can never happen bc C doesn't know the structure of a Go string. Also, I believe this is incorrectly using StringHeader and SliceHeader. You're not supposed to directly convert to and from those types.

**Comment by hajimehoshi** [comment]
@TotallyGamerJet By the way, doesn't auto-type conversion work for return values? We already have a conversion for arguments: https://github.com/ebitengine/purego/blob/main/examples/libc/main.go

**Comment by TeavenX** [comment]
> 

Use `unsafe.Slice` might be more suitable. (I'm too old fashion😂
However, the uintptr point to a C address, so it should not be garbage collected (if it is pure go case, that's a incorrectly usage). And I found a snippet code of google  https://github.com/google/gousb/blob/844d4b8a718f46eb580a7a84afa00eb15c1b7a9a/libusb.go%23L203 which is similar to my case

**Comment by hajimehoshi** [comment]
Ahh, for return values, C and Go values' lifetimes would matter and automatic conversion would not work well...

**Comment by hajimehoshi** [comment]
https://pkg.go.dev/github.com/ebitengine/purego#RegisterFunc

I failed to find a comment about the copying behavior. Does this happen only when converting a C char* to a Go string?

**Comment by TotallyGamerJet** [comment]
True the copying part is not specified. I was referring to the fact that it does define that a char* can be returned from a function as a string. I should probably specify that when returning it does a copy. As well as define the behavior of arguments as well.

**Comment by hajimehoshi** [comment]
@TotallyGamerJet I would appreciate if you could update the current documentation to explain with the current behavior. Thanks,

**Comment by hajimehoshi** [comment]
https://github.com/ebitengine/purego/commit/e5b87e976b386838bf71ee85f2eb03f753bae8b9

As Purego converts a C string to a Go string automatically, I don't think this example is needed...

**Comment by hajimehoshi** [comment]
Let me close this per e5b87e976b386838bf71ee85f2eb03f753bae8b9

**Pull request closed without merging**
