### PR TITLE
arm64 broke

### PR DESCRIPTION
**Pull request by TotallyGamerJet**
I forgot callbackWrapPicker needs to be implemented on arm64

### CODE REVIEW

**Comment by TotallyGamerJet** [comment]
It also might be a good idea to test cross compilation to arm64

**Review by hajimehoshi — COMMENTED** [review]
Can we integrate this and `callback_go1_16_darwin_amd64.go` to `callback_go1_16_darwin.go` ?

**Comment by hajimehoshi** [comment]
> It also might be a good idea to test cross compilation to arm64

I agree. I'm fine you add this in this PR, or I'll do in a later PR.

**Comment by TotallyGamerJet** [comment]
> Can we integrate this and `callback_go1_16_darwin_amd64.go` to `callback_go1_16_darwin.go` ?

We could but it would mean changing the assembly to purposefully make an indirection. Do you want that?

**Comment by hajimehoshi** [comment]
> We could but it would mean changing the assembly to purposefully make an indirection. Do you want that?

I was wondering why we would need assembly changes by integrating... Sorry if I am missing something

**Comment by TotallyGamerJet** [comment]
Because amd64 is using the Go 1.15 mechanism of double indirection (`**callbackArgs`) while arm64 is using 1.16 mechanism of single indirection (`*callbackArgs`). They are not the exact same file.

**Comment by hajimehoshi** [comment]
Aha, I missed such a slight difference. Thank you!

**Review by hajimehoshi — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
