### PR TITLE
rename cgo.go to cgo_darwin.go

### PR DESCRIPTION
**Pull request by TotallyGamerJet**

### CODE REVIEW

**Comment by TotallyGamerJet** [comment]
I'm gonna use Github Actions to test this behavior

**Comment by TotallyGamerJet** [comment]
Well that test did absolutely nothing :(

**Comment by TotallyGamerJet** [comment]
I guess it won't let me test anymore. I'll get a VM to see if I can reproduce this error in the operating systems

**Comment by TotallyGamerJet** [comment]
Cause I'm a little confused as to what is actually failing. I don't think it's the OS itself. Perhaps, cross-compilation?

**Comment by TotallyGamerJet** [comment]
Ok now I'm thoroughly confused. It can't build an empty main on linux?

**Comment by TotallyGamerJet** [comment]
Also, I am unable to reproduce this on a vm. Any luck for you?

**Comment by TotallyGamerJet** [comment]
It's only failing on 1.15 Ubuntu and not the other versions. Why is this?

**Comment by hajimehoshi** [comment]
> It's only failing on 1.15 Ubuntu and not the other versions. Why is this?

I'm not 100% confident but this might be a bug in Go 1.15, which has already been fixed. I think it is OK so far to forbid importing purego for Linux e.g. purego can be imported only from Windows and Darwin.

**Comment by TotallyGamerJet** [comment]
That works. We need to not test 1.15 then on Linux

**Comment by hajimehoshi** [comment]
Hm, the test failure happens cross-building without Cgo?

**Comment by hajimehoshi** [comment]
I think the fix will be like this: https://github.com/ebitengine/purego/compare/main...test

**Comment by TotallyGamerJet** [comment]
@hajimehoshi do you just want to submit that as a PR?

**Comment by hajimehoshi** [comment]
Sure!

**Comment by TotallyGamerJet** [comment]
Closed because solved in #41

**Pull request closed without merging**
