### PR TITLE
.github/workflows: enable go-test with -race for Go 1.21 and the future

### PR DESCRIPTION
**Pull request by hajimehoshi**
Updates #74

### CODE REVIEW

**Comment by hajimehoshi** [comment]
Please take a look

**Comment by hajimehoshi** [comment]
This change also fixes a syntax error.

**Comment by TotallyGamerJet** [comment]
LGTM!

Make sure to include `Updates #74 ` please

**Comment by hajimehoshi** [comment]
Thanks. Please give your approval :-)

image

**Review by TotallyGamerJet — APPROVED** [review]

**Pull request merged**
