### PR TITLE
Increase max argument to 15

### PR DESCRIPTION
**Pull request by TotallyGamerJet**
This increases the max number of arguments to be 15. This is necessary because amd64 puts almost everything on the stack when passing structs. This meant that there wasn't enough room with just 9 arguments to pass all the tests that arm64 has in the struct branch.

### CODE REVIEW

**Comment by TotallyGamerJet** [comment]
I'm looking into why it's failing with `morestack on g0`. It doesn't fail on my machine. @hajimehoshi do you remember how you fixed that for the Switch?

**Comment by hajimehoshi** [comment]
> `morestack on g0`

This should be fixed in 1.21.4 (https://github.com/golang/go/issues/62440). This doesn't occur in 1.20 and older.

**Comment by TotallyGamerJet** [comment]
But the 1.19 test is the one that failed?

**Comment by hajimehoshi** [comment]
> But the 1.19 test is the one that failed?

So unfortunately this seems a different thing from what I've seen in Switch.

**Comment by TotallyGamerJet** [comment]
This is now ready for review!

**Review by hajimehoshi — APPROVED** [review]
LGTM, thanks!

Just out of curiosity, is there a limitation of float argument numbers?

**Comment by TotallyGamerJet** [comment]
No there shouldn't be since once all the float registers are full they get placed on the stack. I'll add a test to this PR to prove that

**Comment by progrium** [comment]
👀

**Comment by hajimehoshi** [comment]
Let me know when this pr is ready

**Comment by TotallyGamerJet** [comment]
@hajimehoshi it is ready to be merged if the new test also looks good

**Pull request merged**
