### PR TITLE
.github/workflows: drop Go 1.15 from the supported environments

### PR DESCRIPTION
**Pull request by hajimehoshi**
Updates #43

### CODE REVIEW

**Comment by hajimehoshi** [comment]
Please take a look!

**Comment by TotallyGamerJet** [comment]
Oh, I was gonna revert the changes that added 1.15 support after this PR. That would probably be easier than manually changing the files since there were some minor assembly changes

**Review by TotallyGamerJet — COMMENTED** [review]
LGTM! What are your thoughts on my comment above?

**Comment by hajimehoshi** [comment]
> Oh, I was gonna revert the changes that added 1.15 support after this PR. That would probably be easier than manually changing the files since there were some minor assembly changes

I see. Wouldn't the changes for go.mod and test.yml work? Should I avoid including the callback files changes?

**Comment by TotallyGamerJet** [comment]
> Wouldn't the changes for go.mod and test.yml work? Should I avoid including the callback files changes?

Keep go.mod and test.yml changes but exclude the callback ones. I'll revert the 1.15 support after this PR is merged

**Comment by hajimehoshi** [comment]
> Keep go.mod and test.yml changes but exclude the callback ones. I'll revert the 1.15 support after this PR is merged

Done!

**Review by TotallyGamerJet — APPROVED** [review]
LGTM!

**Pull request merged**
